In [2]:
import torch
print(torch.__version__)

2.10.0+cpu


In [3]:
import torch
x = torch.tensor([1, 2, 3,4])

print(x)
print(type(x))

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


In [4]:
matrix = torch.tensor([[1, 2],
                       [3, 4]])

print(matrix)


tensor([[1, 2],
        [3, 4]])


In [5]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a + b)
print(a * b)


tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [6]:
import torch

# Create tensor with gradient tracking
x = torch.tensor(2.0, requires_grad=True)

# Function: y = x^2
y = x**2

# Compute gradient
y.backward()

print("x:", x)
print("Gradient dy/dx:", x.grad)


x: tensor(2., requires_grad=True)
Gradient dy/dx: tensor(4.)


In [7]:
import torch 

import torch.nn as nn
import torch.optim as optim


In [8]:
X = torch.tensor([
    [1.0],
    [2.0],
    [3.0],
    [4.0]
])

Y = torch.tensor([[2.0],
                  [4.0],
                  [6.0],
                  [8.0]])


In [9]:
# Define model
model = nn.Linear(in_features=1, out_features=1)


In [10]:
criterion = nn.MSELoss()

optimizer = optim.SGD(model.parameters(), lr=0.01)


In [11]:
epochs = 100

for epoch in range(epochs):

    # Forward pass
    y_pred = model(X)

    # Compute loss
    loss = criterion(y_pred, Y)

    # Backward pass
    loss.backward()

    # Update weights
    optimizer.step()

    # Reset gradients
    optimizer.zero_grad()

    if epoch % 10 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())


Epoch: 0 Loss: 58.21909713745117
Epoch: 10 Loss: 1.5101747512817383
Epoch: 20 Loss: 0.04275219514966011
Epoch: 30 Loss: 0.004572187550365925
Epoch: 40 Loss: 0.0033826360013335943
Epoch: 50 Loss: 0.003161867382004857
Epoch: 60 Loss: 0.0029772119596600533
Epoch: 70 Loss: 0.002803916810080409
Epoch: 80 Loss: 0.0026407039258629084
Epoch: 90 Loss: 0.002486997749656439


In [12]:
import torch
import torch.nn as nn
import torch.optim as optim

X = torch.tensor(
    [
        [1.0],
        [2.0],
        [3.0],
        [4.0],
        [5.0]
    ]
)

Y = torch.tensor(
    [
        [3.0],
        [5.9],
        [7.0],
        [9.0],
        [11.0]
    ]
)

In [16]:
class NeuralNetwork(nn.Module):

    def __init__(self):

        # call parrent constructor

        super(NeuralNetwork, self).__init__()


        # input --> Hidden
        self.hidden = nn.Linear(in_features=1, out_features= 4)

        # hidden --> output 
        self.output = nn.Linear(in_features=4, out_features = 1)

        # activate the function

        self.relu = nn.ReLU()

    
    def forward(self,x):

        x = self.hidden(x)

        x  = self.relu(x)

        x = self.output(x)

        return x


In [17]:
model = NeuralNetwork()

criterion = nn.MSELoss()

optimizer = optim.SGD(model.parameters(), lr=0.01)



In [19]:
epochs = 500

for epoch in range(epochs ):

    predictions = model(X)

    loss = criterion(predictions, Y)

    loss.backward()

    optimizer.step()

    optimizer.zero_grad()

    if epoch % 50 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

Epoch: 0 Loss: 0.09035182744264603
Epoch: 50 Loss: 0.08870483934879303
Epoch: 100 Loss: 0.08721447736024857
Epoch: 150 Loss: 0.0856538787484169
Epoch: 200 Loss: 0.08413958549499512
Epoch: 250 Loss: 0.08267585188150406
Epoch: 300 Loss: 0.0812680572271347
Epoch: 350 Loss: 0.07976483553647995
Epoch: 400 Loss: 0.07846974581480026
Epoch: 450 Loss: 0.0770568996667862


In [21]:
test = torch.tensor([[6.0]])


prediction = model(test)

print("Prediction:", prediction)

Prediction: tensor([[12.7608]], grad_fn=<AddmmBackward0>)


## Next Topic: CNN (Convolutional Neural Networks)

- (A) Convolution Layer
- 
- Detects features like:
- 
- • edges
- • shapes
- • textures

In [22]:
import torch 
import torch.nn as nn
import torch.optim as optim


In [27]:
class CNN(nn.Module):

    def __init__(self):

        super(CNN, self).__init__()

        # con layer
        self.conv1 = nn.Conv2d(1,8,3)

        self.relu = nn.ReLU()

        self.pool = nn.MaxPool2d(2,2)

        self.fc1 = nn.Linear(1352, 10)


    def forward(self, x):

        x = self.conv1(x)

        x = self.relu(x)

        x = self.pool(x)

        x = x.view(x.size(0),-1)


        x = self.fc1(x)

        return x

In [28]:
model = CNN()

In [29]:
criterion = nn.CrossEntropyLoss()

optimizer = optim.Adam(model.parameters(), lr=0.001)



In [30]:
image = torch.randn(1,1,28,28)

output = model(image)

print(output)
print(output.shape)

tensor([[-0.4004, -0.2577,  0.2146,  0.1142,  0.0726, -0.3112,  0.5493, -0.2404,
         -0.1051,  0.5846]], grad_fn=<AddmmBackward0>)
torch.Size([1, 10])


In [ ]:
## full code


import torch
import torch.nn as nn
import torch.optim as optim


# CNN Model
class CNN(nn.Module):

    def __init__(self):

        super(CNN, self).__init__()

        # Convolution layer
        # Input channels = 1
        # Output channels = 8
        # Kernel size = 3
        self.conv1 = nn.Conv2d(1, 8, 3)

        # Activation function
        self.relu = nn.ReLU()

        # Pooling layer
        self.pool = nn.MaxPool2d(2, 2)

        # Fully connected layer
        self.fc1 = nn.Linear(1352, 10)


    def forward(self, x):

        # Apply convolution
        x = self.conv1(x)

        # Apply activation
        x = self.relu(x)

        # Apply pooling
        x = self.pool(x)

        # Flatten tensor
        x = x.view(x.size(0), -1)

        # Fully connected layer
        x = self.fc1(x)

        return x


# Create model
model = CNN()


# Loss function
criterion = nn.CrossEntropyLoss()


# Optimizer
optimizer = optim.Adam(model.parameters(), lr=0.001)


# Example image
image = torch.randn(1, 1, 28, 28)


# Forward pass
output = model(image)


print("Output:", output)
print("Shape:", output.shape)


## What is RNN (Recurrent Neural Network)

## What is LSTM (Long Short-Term Memory)

In [31]:
import torch 
import torch.nn as nn 



In [32]:
class SimpleRNN(nn.Module):

    def __init__(self):

        super(SimpleRNN).__init__()



        self.rnn = nn.RNN(
            input_size = 1,
            hidden_size = 2,
            num_layers = 1
        )

        self.fc = nn.Linear(10,1)

    def forward(self, x):

        out, hidden = self.rnn(x)

        out = out[:,-1,:]

        out = self.fc(out)

        return out

    

In [33]:
torch.Size([2,1])

torch.Size([2, 1])

In [42]:
class SimpleLSTM(nn.Module):

    def __init__(self):

        super(SimpleLSTM, self).__init__()

        # LSTM layer
        self.lstm = nn.LSTM(
            input_size=5,
            hidden_size=10,
            num_layers=1,
            batch_first=True
        )

        # Output layer
        self.fc = nn.Linear(10, 1)


    def forward(self, x):

        # LSTM returns output, hidden, cell state
        out, (hidden, cell) = self.lstm(x)

        # Take last output
        out = out[:, -1, :]

        # Fully connected layer
        out = self.fc(out)

        return out

In [43]:
model = SimpleLSTM()

x = torch.randn(2,3,5)

output = model(x)

print(output.shape)
print(output)

torch.Size([2, 1])
tensor([[-0.1494],
        [-0.2110]], grad_fn=<AddmmBackward0>)


In [44]:
import torch
import torch.nn as nn


class SimpleLSTM(nn.Module):

    def __init__(self):

        super(SimpleLSTM, self).__init__()

        # LSTM layer
        # input_size = number of features
        # hidden_size = memory size
        # num_layers = stacked LSTM layers
        self.lstm = nn.LSTM(
            input_size=5,
            hidden_size=10,
            num_layers=1,
            batch_first=True
        )

        # Fully connected layer
        self.fc = nn.Linear(10, 1)


    def forward(self, x):

        # Pass input through LSTM
        out, (hidden, cell) = self.lstm(x)

        # Take output from last time step
        out = out[:, -1, :]

        # Pass through output layer
        out = self.fc(out)

        return out


# Create model
model = SimpleLSTM()

# Example input
x = torch.randn(2, 3, 5)

# Forward pass
output = model(x)

print("Output:", output)
print("Shape:", output.shape)


Output: tensor([[-0.2637],
        [-0.2452]], grad_fn=<AddmmBackward0>)
Shape: torch.Size([2, 1])


In [45]:
import torch 
import torch.nn as nn


In [51]:
class SimpleTransformer(nn.Module):

    def __init__(self):

        super(SimpleTransformer, self).__init__()

        # Embedding layer
        self.embedding = nn.Embedding(
            num_embeddings=100,  # vocabulary size
            embedding_dim=32     # vector size
        )

        # Transformer encoder layer
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=32,
            nhead=4
        )

        # Transformer encoder
        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=2
        )

        # Output layer
        self.fc = nn.Linear(32, 1)


    def forward(self, x):

        # Convert words to embeddings
        x = self.embedding(x)

        # Transformer expects shape:
        # (sequence, batch, embedding)
        x = x.permute(1, 0, 2)

        # Pass through transformer
        x = self.transformer(x)

        # Take last output
        x = x[-1]

        # Fully connected layer
        x = self.fc(x)

        return x


In [52]:
model = SimpleTransformer()

# Example input
# batch size = 2
# sequence length = 5
x = torch.randint(0, 100, (2, 5))

output = model(x)

print(output)
print(output.shape)


tensor([[ 0.0801],
        [-0.0916]], grad_fn=<AddmmBackward0>)
torch.Size([2, 1])


C:\Users\mohda\AppData\Local\Temp\ipykernel_12284\1097073835.py:20: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  self.transformer = nn.TransformerEncoder(


In [53]:
import torch
import torch.nn as nn


class SimpleTransformer(nn.Module):

    def __init__(self):

        super(SimpleTransformer, self).__init__()

        # Embedding layer converts tokens → vectors
        self.embedding = nn.Embedding(100, 32)

        # Transformer encoder layer
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=32,   # embedding size
            nhead=4       # attention heads
        )

        # Stack encoder layers
        self.transformer = nn.TransformerEncoder(
            encoder_layer,
            num_layers=2
        )

        # Output layer
        self.fc = nn.Linear(32, 1)


    def forward(self, x):

        # Convert token → embedding
        x = self.embedding(x)

        # Change shape for transformer
        x = x.permute(1, 0, 2)

        # Transformer processing
        x = self.transformer(x)

        # Take last token output
        x = x[-1]

        # Final output
        x = self.fc(x)

        return x


# Create model
model = SimpleTransformer()

# Example input
x = torch.randint(0, 100, (2, 5))

# Forward pass
output = model(x)

print("Output:", output)
print("Shape:", output.shape)


Output: tensor([[-0.2694],
        [ 0.6625]], grad_fn=<AddmmBackward0>)
Shape: torch.Size([2, 1])


C:\Users\mohda\AppData\Local\Temp\ipykernel_12284\1416521066.py:21: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  self.transformer = nn.TransformerEncoder(
